services:
  app:
    # 로드된 이미지 이름과 태그
    image: rps-game-app:latest
    container_name: rps-game
    ports:
      - '3005:3005'
    restart: unless-stopped
    environment:
      - NODE_ENV: production
